services:
  rssfeed:
    image: ${DOCKER_IMAGE:-thititongumpun/elysia-rssfeed}:${CONTAINER_VERSION:-latest}
    container_name: rssfeed
    restart: always
    env_file:
      - path: .env
    environment:
      - TZ=Asia/Bangkok