name: Cleanup n8n Executions

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch: 

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run cleanup SQL
        env:
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}
        run: |
          echo "Backing up executions older than 3 days..."
          psql -h ${{ secrets.PG_HOST }} \
               -U ${{ secrets.PG_USER }} \
               -d postgres \
               -p 5432 \
               -c "DELETE FROM execution_entity WHERE \"stoppedAt\" < NOW() - INTERVAL '3 days' LIMIT 100;"
          echo "Done."
